version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-v1-{{ .Branch }}-{{ .Revision }}
        - repo-v1-{{ .Branch }}
        - repo-v1-

  restore_npm_install: &restore_npm_install
    restore_cache:
      keys:
        - node_modules-v1-cache-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - node_modules-v1-cache

  restore_dynamodb_local: &restore_dynamodb_local
    restore_cache:
      keys:
        - dynamodblocal-v2

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: repo-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  dynamodb_local_setup:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_dynamodb_local
      - run:
          name: "Downlad and install"
          command: |
            mkdir dynamodb_local
            cd dynamodb_local
            curl -k -L -o dynamodb-local.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
            tar -xzf dynamodb-local.tgz
            cd ..
      - save_cache:
          key: dynamodblocal-v2
          paths:
            - ./dynamodb_local


  npm_install:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_npm_install
      - run:
          name: "npm install"
          command: npm install --update-binary
      - save_cache:
          key: node_modules-v1-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  lint:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_npm_install
      - run:
          name: "Linting"
          command: npm run lint -- --format junit -o reports/junit/js-lint-results.xml

  test:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_npm_install
      - *restore_dynamodb_local
      - run:
          name: "Start dynamodb local"
          command: |
            sudo apt-get install default-jre --assume-yes
            java -Djava.library.path=./dynamodb_local/DynamoDBLocal_lib -jar DynamoDBLocal.jar -port 2018 -inMemory
      - run:
          name: "Test suite execution"
          command: ./node_modules/jest/bin/jest.js --ci --testResultsProcessor="jest-junit" --collectCoverage --coverageReporters="lcov"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: "Test suite execution"
          command: npm run test -- --ci --testResultsProcessor="jest-junit" --collectCoverage --coverageReporters="lcov"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: "Report to codecov.io"
          command: ./node_modules/codecov/bin/codecov

      - store_test_results: #along with linting results
          path: reports/junit

      - store_artifacts:
          path: reports/junit

      - store_artifacts:
          path: coverage

workflows:
  version: 2
  main:
    jobs:
      - checkout_code
      - dynamodb_local_setup:
          requires:
            - checkout_code
      - npm_install:
          requires:
            - checkout_code
      - lint:
          requires:
            - npm_install
      - test:
          requires:
            - npm_install
            - dynamodb_local_setup
